export const GET_ERRORS="GET_ERRORS";
export const GET_PROJECTS="GET_PROJECTS";
export const GET_PROJECT="GET_PROJECT";
export const DELETE_PROJECT="DELETE_PROJECT";
export const UPDATE_PROJECT="UPDATE_PROJECT";

export const GET_TASK_ERRORS="GET_TASK_ERRORS";
export const GET_TASKS="GET_TASKS";
export const GET_TASK="GET_TASK";
export const DELETE_TASK="DELETE_TASK";
export const UPDATE_TASK="UPDATE_TASK";